# Site settings
title: Lunar Rabbit
description: >
  Lunar Rabbit Games is an independent game studio located in Philadelphia, born 
  out of the Entrepreneurial Game Studio at Drexel University. We are a group of 
  students across multiple disciplines looking to create unique and beautiful games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lunarrabbit.com" # the base hostname & protocol for your site
email: lunarrabbitgames@gmail.com
twitter_url: https://twitter.com/lunarrabbitdev
tumblr_url: http://starbrightdevelopment.tumblr.com/
facebook_url: https://www.facebook.com/Lunar-Rabbit-Games-1579254689030384/

# Build settings
markdown: kramdown
