# Site settings
title: Lunar Rabbit
email: lunarrabbitgames@gmail.com
description: >
  Lunar Rabbit is an independant game company in Phialdelphia, born
  out of the Entrapenurial Game Studio of Drexel University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lunarrabbit.com" # the base hostname & protocol for your site
twitter_username: lunarrabbitdev
tumblr_url:
facebook_url:

# Build settings
markdown: kramdown
